import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter, Space_Mono, Work_Sans } from "next/font/google";
import Footer from "@/components/Footer";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });
const space_mono = Space_Mono({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
  variable: "--font-space-mono",
});
const work_sans = Work_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600"],
  variable: "--font-work-sans",
});

export const metadata = {
  title: "NFT Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
      </Head>
      <body className={`${space_mono.variable} ${work_sans.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
